apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: manifest-source
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/tofflos/red-hat-fuse-console.git
